import "package:flutter/material.dart";
import "package:google_fonts/google_fonts.dart";
import "package:treinamento_flutter/app/utils/scale_sizer.dart";

part 'utils.g.dart';
part 'custom_colors.g.dart';
part 'custom_theme_extension.g.dart';

class AppTheme {

  static ColorScheme lightScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff095da8),
      surfaceTint: Color(0xff105faa),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xff3476c2),
      onPrimaryContainer: Color(0xfffefcff),
      secondary: Color(0xff00244a),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xff003a70),
      onSecondaryContainer: Color(0xff7ea5e2),
      tertiary: Color(0xff745b00),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xffffcb05),
      onTertiaryContainer: Color(0xff6f5700),
      error: Color(0xffb7121c),
      onError: Color(0xffffffff),
      errorContainer: Color(0xffdb3131),
      onErrorContainer: Color(0xfffffbff),
      surface: Color(0xfffcf8f8),
      onSurface: Color(0xff1c1b1b),
      onSurfaceVariant: Color(0xff434749),
      outline: Color(0xff737879),
      outlineVariant: Color(0xffc3c7c9),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff313030),
      inversePrimary: Color(0xffa5c8ff),
      primaryFixed: Color(0xffd4e3ff),
      onPrimaryFixed: Color(0xff001c3a),
      primaryFixedDim: Color(0xffa5c8ff),
      onPrimaryFixedVariant: Color(0xff004785),
      secondaryFixed: Color(0xffd5e3ff),
      onSecondaryFixed: Color(0xff001c3b),
      secondaryFixedDim: Color(0xffa6c8ff),
      onSecondaryFixedVariant: Color(0xff18477e),
      tertiaryFixed: Color(0xffffe08d),
      onTertiaryFixed: Color(0xff241a00),
      tertiaryFixedDim: Color(0xfff2c000),
      onTertiaryFixedVariant: Color(0xff584400),
      surfaceDim: Color(0xffddd9d9),
      surfaceBright: Color(0xfffcf8f8),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfff6f3f2),
      surfaceContainer: Color(0xfff1edec),
      surfaceContainerHigh: Color(0xffebe7e7),
      surfaceContainerHighest: Color(0xffe5e2e1),
    );
  }

  ThemeData light(BuildContext context) {
    return theme(lightScheme(), context);
  }

  static ColorScheme lightMediumContrastScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff003768),
      surfaceTint: Color(0xff105faa),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xff2a6eba),
      onPrimaryContainer: Color(0xffffffff),
      secondary: Color(0xff00244a),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xff003a70),
      onSecondaryContainer: Color(0xffafcdff),
      tertiary: Color(0xff443400),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xff866900),
      onTertiaryContainer: Color(0xffffffff),
      error: Color(0xff73000a),
      onError: Color(0xffffffff),
      errorContainer: Color(0xffd1292b),
      onErrorContainer: Color(0xffffffff),
      surface: Color(0xfffcf8f8),
      onSurface: Color(0xff111111),
      onSurfaceVariant: Color(0xff323738),
      outline: Color(0xff4f5355),
      outlineVariant: Color(0xff696e6f),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff313030),
      inversePrimary: Color(0xffa5c8ff),
      primaryFixed: Color(0xff2a6eba),
      onPrimaryFixed: Color(0xffffffff),
      primaryFixedDim: Color(0xff00559d),
      onPrimaryFixedVariant: Color(0xffffffff),
      secondaryFixed: Color(0xff456ea7),
      onSecondaryFixed: Color(0xffffffff),
      secondaryFixedDim: Color(0xff2a568d),
      onSecondaryFixedVariant: Color(0xffffffff),
      tertiaryFixed: Color(0xff866900),
      onTertiaryFixed: Color(0xffffffff),
      tertiaryFixedDim: Color(0xff695200),
      onTertiaryFixedVariant: Color(0xffffffff),
      surfaceDim: Color(0xffc9c6c5),
      surfaceBright: Color(0xfffcf8f8),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfff6f3f2),
      surfaceContainer: Color(0xffebe7e7),
      surfaceContainerHigh: Color(0xffdfdcdb),
      surfaceContainerHighest: Color(0xffd4d1d0),
    );
  }

  ThemeData lightMediumContrast(BuildContext context) {
    return theme(lightMediumContrastScheme(), context);
  }

  static ColorScheme lightHighContrastScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff002d57),
      surfaceTint: Color(0xff105faa),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xff004a89),
      onPrimaryContainer: Color(0xffffffff),
      secondary: Color(0xff00244a),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xff003a70),
      onSecondaryContainer: Color(0xfffdfbff),
      tertiary: Color(0xff382a00),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xff5b4700),
      onTertiaryContainer: Color(0xffffffff),
      error: Color(0xff600007),
      onError: Color(0xffffffff),
      errorContainer: Color(0xff980010),
      onErrorContainer: Color(0xffffffff),
      surface: Color(0xfffcf8f8),
      onSurface: Color(0xff000000),
      onSurfaceVariant: Color(0xff000000),
      outline: Color(0xff282d2e),
      outlineVariant: Color(0xff454a4b),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff313030),
      inversePrimary: Color(0xffa5c8ff),
      primaryFixed: Color(0xff004a89),
      onPrimaryFixed: Color(0xffffffff),
      primaryFixedDim: Color(0xff003362),
      onPrimaryFixedVariant: Color(0xffffffff),
      secondaryFixed: Color(0xff1b4a80),
      onSecondaryFixed: Color(0xffffffff),
      secondaryFixedDim: Color(0xff003363),
      onSecondaryFixedVariant: Color(0xffffffff),
      tertiaryFixed: Color(0xff5b4700),
      onTertiaryFixed: Color(0xffffffff),
      tertiaryFixedDim: Color(0xff403100),
      onTertiaryFixedVariant: Color(0xffffffff),
      surfaceDim: Color(0xffbbb8b7),
      surfaceBright: Color(0xfffcf8f8),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfff4f0ef),
      surfaceContainer: Color(0xffe5e2e1),
      surfaceContainerHigh: Color(0xffd7d4d3),
      surfaceContainerHighest: Color(0xffc9c6c5),
    );
  }

  ThemeData lightHighContrast(BuildContext context) {
    return theme(lightHighContrastScheme(), context);
  }

  static ColorScheme darkScheme() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xffa5c8ff),
      surfaceTint: Color(0xffa5c8ff),
      onPrimary: Color(0xff00315e),
      primaryContainer: Color(0xff5593e1),
      onPrimaryContainer: Color(0xff001025),
      secondary: Color(0xffa6c8ff),
      onSecondary: Color(0xff00315f),
      secondaryContainer: Color(0xff003a70),
      onSecondaryContainer: Color(0xff7ea5e2),
      tertiary: Color(0xffffecc1),
      onTertiary: Color(0xff3d2f00),
      tertiaryContainer: Color(0xffffcb05),
      onTertiaryContainer: Color(0xff6f5700),
      error: Color(0xffffb3ac),
      onError: Color(0xff680008),
      errorContainer: Color(0xffdb3131),
      onErrorContainer: Color(0xfffffbff),
      surface: Color(0xff141313),
      onSurface: Color(0xffe5e2e1),
      onSurfaceVariant: Color(0xffc3c7c9),
      outline: Color(0xff8d9193),
      outlineVariant: Color(0xff434749),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xffe5e2e1),
      inversePrimary: Color(0xff105faa),
      primaryFixed: Color(0xffd4e3ff),
      onPrimaryFixed: Color(0xff001c3a),
      primaryFixedDim: Color(0xffa5c8ff),
      onPrimaryFixedVariant: Color(0xff004785),
      secondaryFixed: Color(0xffd5e3ff),
      onSecondaryFixed: Color(0xff001c3b),
      secondaryFixedDim: Color(0xffa6c8ff),
      onSecondaryFixedVariant: Color(0xff18477e),
      tertiaryFixed: Color(0xffffe08d),
      onTertiaryFixed: Color(0xff241a00),
      tertiaryFixedDim: Color(0xfff2c000),
      onTertiaryFixedVariant: Color(0xff584400),
      surfaceDim: Color(0xff141313),
      surfaceBright: Color(0xff3a3939),
      surfaceContainerLowest: Color(0xff0e0e0e),
      surfaceContainerLow: Color(0xff1c1b1b),
      surfaceContainer: Color(0xff201f1f),
      surfaceContainerHigh: Color(0xff2a2a2a),
      surfaceContainerHighest: Color(0xff353434),
    );
  }

  ThemeData dark(BuildContext context) {
    return theme(darkScheme(), context);
  }

  static ColorScheme darkMediumContrastScheme() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xffcaddff),
      surfaceTint: Color(0xffa5c8ff),
      onPrimary: Color(0xff00264b),
      primaryContainer: Color(0xff5593e1),
      onPrimaryContainer: Color(0xff000000),
      secondary: Color(0xffcbddff),
      onSecondary: Color(0xff00264c),
      secondaryContainer: Color(0xff6a92cd),
      onSecondaryContainer: Color(0xff000000),
      tertiary: Color(0xffffecc1),
      onTertiary: Color(0xff3d2f00),
      tertiaryContainer: Color(0xffffcb05),
      onTertiaryContainer: Color(0xff4d3b00),
      error: Color(0xffffd2cd),
      onError: Color(0xff540005),
      errorContainer: Color(0xffff544e),
      onErrorContainer: Color(0xff000000),
      surface: Color(0xff141313),
      onSurface: Color(0xffffffff),
      onSurfaceVariant: Color(0xffd9ddde),
      outline: Color(0xffaeb2b4),
      outlineVariant: Color(0xff8d9192),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xffe5e2e1),
      inversePrimary: Color(0xff004987),
      primaryFixed: Color(0xffd4e3ff),
      onPrimaryFixed: Color(0xff001128),
      primaryFixedDim: Color(0xffa5c8ff),
      onPrimaryFixedVariant: Color(0xff003768),
      secondaryFixed: Color(0xffd5e3ff),
      onSecondaryFixed: Color(0xff001128),
      secondaryFixedDim: Color(0xffa6c8ff),
      onSecondaryFixedVariant: Color(0xff003669),
      tertiaryFixed: Color(0xffffe08d),
      onTertiaryFixed: Color(0xff171000),
      tertiaryFixedDim: Color(0xfff2c000),
      onTertiaryFixedVariant: Color(0xff443400),
      surfaceDim: Color(0xff141313),
      surfaceBright: Color(0xff454444),
      surfaceContainerLowest: Color(0xff070707),
      surfaceContainerLow: Color(0xff1e1d1d),
      surfaceContainer: Color(0xff282828),
      surfaceContainerHigh: Color(0xff333232),
      surfaceContainerHighest: Color(0xff3e3d3d),
    );
  }

  ThemeData darkMediumContrast(BuildContext context) {
    return theme(darkMediumContrastScheme(), context);
  }

  static ColorScheme darkHighContrastScheme() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xffeaf0ff),
      surfaceTint: Color(0xffa5c8ff),
      onPrimary: Color(0xff000000),
      primaryContainer: Color(0xff9ec5ff),
      onPrimaryContainer: Color(0xff000b1e),
      secondary: Color(0xffeaf0ff),
      onSecondary: Color(0xff000000),
      secondaryContainer: Color(0xff9fc4ff),
      onSecondaryContainer: Color(0xff000b1e),
      tertiary: Color(0xffffefca),
      onTertiary: Color(0xff000000),
      tertiaryContainer: Color(0xffffcb05),
      onTertiaryContainer: Color(0xff261c00),
      error: Color(0xffffece9),
      onError: Color(0xff000000),
      errorContainer: Color(0xffffaea6),
      onErrorContainer: Color(0xff220001),
      surface: Color(0xff141313),
      onSurface: Color(0xffffffff),
      onSurfaceVariant: Color(0xffffffff),
      outline: Color(0xffedf0f2),
      outlineVariant: Color(0xffbfc3c5),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xffe5e2e1),
      inversePrimary: Color(0xff004987),
      primaryFixed: Color(0xffd4e3ff),
      onPrimaryFixed: Color(0xff000000),
      primaryFixedDim: Color(0xffa5c8ff),
      onPrimaryFixedVariant: Color(0xff001128),
      secondaryFixed: Color(0xffd5e3ff),
      onSecondaryFixed: Color(0xff000000),
      secondaryFixedDim: Color(0xffa6c8ff),
      onSecondaryFixedVariant: Color(0xff001128),
      tertiaryFixed: Color(0xffffe08d),
      onTertiaryFixed: Color(0xff000000),
      tertiaryFixedDim: Color(0xfff2c000),
      onTertiaryFixedVariant: Color(0xff171000),
      surfaceDim: Color(0xff141313),
      surfaceBright: Color(0xff51504f),
      surfaceContainerLowest: Color(0xff000000),
      surfaceContainerLow: Color(0xff201f1f),
      surfaceContainer: Color(0xff313030),
      surfaceContainerHigh: Color(0xff3c3b3b),
      surfaceContainerHighest: Color(0xff474646),
    );
  }

  ThemeData darkHighContrast(BuildContext context) {
    return theme(darkHighContrastScheme(), context);
  }

  ThemeData theme(ColorScheme colorScheme, BuildContext context) =>
      ThemeData(
        useMaterial3: true,
        brightness: colorScheme.brightness,
        colorScheme: colorScheme,
        textTheme: createTextTheme(context, "Poppins", "Poppins", colorScheme).apply(fontSizeFactor: ScaleSize.textScaleFactor(context)),
        radioTheme: _getRadioTheme(colorScheme),
        elevatedButtonTheme: _getElevatedButtonTheme(colorScheme),
        inputDecorationTheme: _getInputDecorationTheme(colorScheme),
        scaffoldBackgroundColor: colorScheme.surface,
        extensions: <ThemeExtension<CustomThemeExtension>>[
          CustomThemeExtension(
              success: success,
              info: info,
              pink: pink,
              purple: purple,
              coldLight: coldLight,
              fire: fire,
              neutralDark: neutralDark
          ),
        ],
        canvasColor: colorScheme.surface,
      );
}